languages:
   Ruby: true
engines:
 rubocop:
   enabled: true
   checks:
     Rubocop/Style/StringLiterals:
       enabled: false
 coffeelint:
   enabled: true
exclude_paths:
- "**/vendor/**/*"
- "config/initializers/patches/**/*.rb"
ratings:
   paths:
   - "app/**/*"
   - "lib/**/*"
   - "**.rb"

