languages:
   Ruby: true

engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/StringLiterals:
        enabled: false
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true

exclude_paths:
- "**/vendor/**/*"
- "config/initializers/patches/**/*.rb"
- "spec/teaspoon_env.rb"
- "public/**/*"

ratings:
   paths:
   - "app/**/*"
   - "lib/**/*"
   - "**.rb"


