production:
  sessions:
    default:
      database: priphea-production
      hosts:
        - localhost:27017

development:
  sessions:
    default:
      database: priphea-development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: priphea-development
      hosts:
        - localhost:27017
