library_path: /Users/steve/fakemusiclib
cover_art_cache: /Users/steve/.priphea/cover_art_cache
scanning_threads: 1
database_backups_location: /Users/steve/.priphea/database_backups
swinsian_library: /Users/steve/Library/Application Support/Swinsian/Library.sqlite
